# Generated by Django 3.2.18 on 2023-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230311_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default='kerry tour', max_length=250),
        ),
    ]
