# Generated by Django 3.2.18 on 2023-03-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='tour',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.CharField(choices=[('1', 'One Seat'), ('2', 'Two seats'), ('3', 'Three seats'), ('4', 'Four seats'), ('5', 'Four seats')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_seats',
            field=models.IntegerField(default=15),
        ),
    ]
