# Generated by Django 3.2.18 on 2023-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='is_valid',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.IntegerField(),
        ),
    ]
