# Generated by Django 3.2.18 on 2023-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_number_of_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_seats',
        ),
    ]
