# Generated by Django 3.2.18 on 2023-03-27 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_number_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Please enter a valid phone number,e.g. +123456789. Up to 13 digits allowed.', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}$')]),
        ),
    ]
