# Generated by Django 3.2.18 on 2023-03-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approved',
        ),
    ]
