# Generated by Django 3.2.18 on 2023-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
