# Generated by Django 3.2.18 on 2023-03-27 20:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_postmodel_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/slava-cloud/image/upload/v1678551831/fdtwqu2ujy6t6elu5tyc.jpg', max_length=255, null=True, verbose_name='blog_image'),
        ),
    ]
